{"uid":"f1be707fdd2f670d","name":"test_decorator_labels","fullName":"tests.test_labels#test_decorator_labels","historyId":"c523cdf50b1089ff2e96a47805a8515c","time":{"start":1744395083284,"stop":1744395083491,"duration":207},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n#0 0x557fa6b36e6a <unknown>\n#1 0x557fa65e8640 <unknown>\n#2 0x557fa662211b <unknown>\n#3 0x557fa661de6f <unknown>\n#4 0x557fa666e0ce <unknown>\n#5 0x557fa666d5f6 <unknown>\n#6 0x557fa665f523 <unknown>\n#7 0x557fa662bef3 <unknown>\n#8 0x557fa662cb51 <unknown>\n#9 0x557fa6afbd2b <unknown>\n#10 0x557fa6affc01 <unknown>\n#11 0x557fa6ae3512 <unknown>\n#12 0x557fa6b00774 <unknown>\n#13 0x557fa6ac790f <unknown>\n#14 0x557fa6b24fb8 <unknown>\n#15 0x557fa6b25196 <unknown>\n#16 0x557fa6b35cb6 <unknown>\n#17 0x7fa5ff29caa4 <unknown>\n#18 0x7fa5ff329c3c <unknown>","statusTrace":"@allure.tag(\"web\")\n    @allure.severity(Severity.CRITICAL)\n    @allure.label(\"owner\", \"YAQA\")\n    @allure.feature(\"Задачи в репозитории\")\n    @allure.story(\"Проверяем текст Issue\")\n    @allure.link(\"https://github.com\", name=\"Testing\")\n    def test_decorator_labels():\n        with allure.step(\"Открываем главную страницу\"):\n>           browser.open(\"https://github.com\")\n\ntests/test_labels.py:39: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/_browser.py:93: in open\n    self.config._executor.get_url(relative_or_absolute_url)\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/configuration.py:263: in get_url\n    self.config._driver_get_url_strategy(self.config)(url)\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/configuration.py:178: in get\n    driver = config.driver\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/configuration.py:305: in __get__\n    driver = config.build_driver_strategy(config)\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/configuration.py:129: in _build_local_driver_by_name_or_remote_by_url_and_options\n    return {  # type: ignore\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/configuration.py:66: in build_chrome\n    return Chrome(\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/chrome/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/chromium/webdriver.py:66: in __init__\n    super().__init__(command_executor=executor, options=options)\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:250: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:342: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:429: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fcf094b6710>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"session not created\",\"message\":\"session not created: probably user data d...\\\\n#16 0x557fa6b35cb6 \\\\u003Cunknown>\\\\n#17 0x7fa5ff29caa4 \\\\u003Cunknown>\\\\n#18 0x7fa5ff329c3c \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nE       Stacktrace:\nE       #0 0x557fa6b36e6a <unknown>\nE       #1 0x557fa65e8640 <unknown>\nE       #2 0x557fa662211b <unknown>\nE       #3 0x557fa661de6f <unknown>\nE       #4 0x557fa666e0ce <unknown>\nE       #5 0x557fa666d5f6 <unknown>\nE       #6 0x557fa665f523 <unknown>\nE       #7 0x557fa662bef3 <unknown>\nE       #8 0x557fa662cb51 <unknown>\nE       #9 0x557fa6afbd2b <unknown>\nE       #10 0x557fa6affc01 <unknown>\nE       #11 0x557fa6ae3512 <unknown>\nE       #12 0x557fa6b00774 <unknown>\nE       #13 0x557fa6ac790f <unknown>\nE       #14 0x557fa6b24fb8 <unknown>\nE       #15 0x557fa6b25196 <unknown>\nE       #16 0x557fa6b35cb6 <unknown>\nE       #17 0x7fa5ff29caa4 <unknown>\nE       #18 0x7fa5ff329c3c <unknown>\n\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py:232: SessionNotCreatedException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n#0 0x557fa6b36e6a <unknown>\n#1 0x557fa65e8640 <unknown>\n#2 0x557fa662211b <unknown>\n#3 0x557fa661de6f <unknown>\n#4 0x557fa666e0ce <unknown>\n#5 0x557fa666d5f6 <unknown>\n#6 0x557fa665f523 <unknown>\n#7 0x557fa662bef3 <unknown>\n#8 0x557fa662cb51 <unknown>\n#9 0x557fa6afbd2b <unknown>\n#10 0x557fa6affc01 <unknown>\n#11 0x557fa6ae3512 <unknown>\n#12 0x557fa6b00774 <unknown>\n#13 0x557fa6ac790f <unknown>\n#14 0x557fa6b24fb8 <unknown>\n#15 0x557fa6b25196 <unknown>\n#16 0x557fa6b35cb6 <unknown>\n#17 0x7fa5ff29caa4 <unknown>\n#18 0x7fa5ff329c3c <unknown>","statusTrace":"@allure.tag(\"web\")\n    @allure.severity(Severity.CRITICAL)\n    @allure.label(\"owner\", \"YAQA\")\n    @allure.feature(\"Задачи в репозитории\")\n    @allure.story(\"Проверяем текст Issue\")\n    @allure.link(\"https://github.com\", name=\"Testing\")\n    def test_decorator_labels():\n        with allure.step(\"Открываем главную страницу\"):\n>           browser.open(\"https://github.com\")\n\ntests/test_labels.py:39: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/_browser.py:93: in open\n    self.config._executor.get_url(relative_or_absolute_url)\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/configuration.py:263: in get_url\n    self.config._driver_get_url_strategy(self.config)(url)\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/configuration.py:178: in get\n    driver = config.driver\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/configuration.py:305: in __get__\n    driver = config.build_driver_strategy(config)\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/configuration.py:129: in _build_local_driver_by_name_or_remote_by_url_and_options\n    return {  # type: ignore\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/configuration.py:66: in build_chrome\n    return Chrome(\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/chrome/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/chromium/webdriver.py:66: in __init__\n    super().__init__(command_executor=executor, options=options)\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:250: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:342: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:429: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fcf094b6710>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"session not created\",\"message\":\"session not created: probably user data d...\\\\n#16 0x557fa6b35cb6 \\\\u003Cunknown>\\\\n#17 0x7fa5ff29caa4 \\\\u003Cunknown>\\\\n#18 0x7fa5ff329c3c \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nE       Stacktrace:\nE       #0 0x557fa6b36e6a <unknown>\nE       #1 0x557fa65e8640 <unknown>\nE       #2 0x557fa662211b <unknown>\nE       #3 0x557fa661de6f <unknown>\nE       #4 0x557fa666e0ce <unknown>\nE       #5 0x557fa666d5f6 <unknown>\nE       #6 0x557fa665f523 <unknown>\nE       #7 0x557fa662bef3 <unknown>\nE       #8 0x557fa662cb51 <unknown>\nE       #9 0x557fa6afbd2b <unknown>\nE       #10 0x557fa6affc01 <unknown>\nE       #11 0x557fa6ae3512 <unknown>\nE       #12 0x557fa6b00774 <unknown>\nE       #13 0x557fa6ac790f <unknown>\nE       #14 0x557fa6b24fb8 <unknown>\nE       #15 0x557fa6b25196 <unknown>\nE       #16 0x557fa6b35cb6 <unknown>\nE       #17 0x7fa5ff29caa4 <unknown>\nE       #18 0x7fa5ff329c3c <unknown>\n\n/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py:232: SessionNotCreatedException","steps":[{"name":"Открываем главную страницу","time":{"start":1744395083284,"stop":1744395083489,"duration":205},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n#0 0x557fa6b36e6a <unknown>\n#1 0x557fa65e8640 <unknown>\n#2 0x557fa662211b <unknown>\n#3 0x557fa661de6f <unknown>\n#4 0x557fa666e0ce <unknown>\n#5 0x557fa666d5f6 <unknown>\n#6 0x557fa665f523 <unknown>\n#7 0x557fa662bef3 <unknown>\n#8 0x557fa662cb51 <unknown>\n#9 0x557fa6afbd2b <unknown>\n#10 0x557fa6affc01 <unknown>\n#11 0x557fa6ae3512 <unknown>\n#12 0x557fa6b00774 <unknown>\n#13 0x557fa6ac790f <unknown>\n#14 0x557fa6b24fb8 <unknown>\n#15 0x557fa6b25196 <unknown>\n#16 0x557fa6b35cb6 <unknown>\n#17 0x7fa5ff29caa4 <unknown>\n#18 0x7fa5ff329c3c <unknown>\n\n","statusTrace":"  File \"/home/runner/work/allure_reports/allure_reports/tests/test_labels.py\", line 39, in test_decorator_labels\n    browser.open(\"https://github.com\")\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/_browser.py\", line 93, in open\n    self.config._executor.get_url(relative_or_absolute_url)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/configuration.py\", line 263, in get_url\n    self.config._driver_get_url_strategy(self.config)(url)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/configuration.py\", line 178, in get\n    driver = config.driver\n             ^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/configuration.py\", line 305, in __get__\n    driver = config.build_driver_strategy(config)\n  File \"/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/configuration.py\", line 129, in _build_local_driver_by_name_or_remote_by_url_and_options\n    return {  # type: ignore\n           ~~~~~~~~~~~~~~~~~\n    ...<32 lines>...\n        )\n        ~\n    )()\n    ~^^\n  File \"/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selene/core/configuration.py\", line 66, in build_chrome\n    return Chrome(\n        service=config.driver_service or ChromeService(),\n        options=config.driver_options,\n    )\n  File \"/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n    ~~~~~~~~~~~~~~~~^\n        browser_name=DesiredCapabilities.CHROME[\"browserName\"],\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n        keep_alive=keep_alive,\n        ^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/chromium/webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 250, in __init__\n    self.start_session(capabilities)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 342, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":1,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"severity","value":"critical"},{"name":"story","value":"Проверяем текст Issue"},{"name":"tag","value":"web"},{"name":"feature","value":"Задачи в репозитории"},{"name":"owner","value":"YAQA"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_labels"},{"name":"host","value":"fv-az2210-346"},{"name":"thread","value":"2472-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_labels"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[{"name":"Testing","url":"https://github.com","type":"link"}],"hidden":false,"retry":false,"extra":{"severity":"critical","owner":"YAQA","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"53e216cef7264e3","reportUrl":"https://csprolp.github.io/allure_reports/2//#testresult/53e216cef7264e3","status":"broken","statusDetails":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n#0 0x55ad7d10ce6a <unknown>\n#1 0x55ad7cbbe640 <unknown>\n#2 0x55ad7cbf811b <unknown>\n#3 0x55ad7cbf3e6f <unknown>\n#4 0x55ad7cc440ce <unknown>\n#5 0x55ad7cc435f6 <unknown>\n#6 0x55ad7cc35523 <unknown>\n#7 0x55ad7cc01ef3 <unknown>\n#8 0x55ad7cc02b51 <unknown>\n#9 0x55ad7d0d1d2b <unknown>\n#10 0x55ad7d0d5c01 <unknown>\n#11 0x55ad7d0b9512 <unknown>\n#12 0x55ad7d0d6774 <unknown>\n#13 0x55ad7d09d90f <unknown>\n#14 0x55ad7d0fafb8 <unknown>\n#15 0x55ad7d0fb196 <unknown>\n#16 0x55ad7d10bcb6 <unknown>\n#17 0x7f314a09caa4 <unknown>\n#18 0x7f314a129c3c <unknown>","time":{"start":1744394460057,"stop":1744394460318,"duration":261}}]},"tags":["web"]},"source":"f1be707fdd2f670d.json","parameterValues":[]}